// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxPrinterBis: IconDefinition = {
  name: 'lx-printer',
  theme: 'bis',
  icon:
    '<svg viewBox="0 0 1024 1024"><path fill="#0942F0" d="M748 664V548a20 20 0 0 0-20-20H308a20 20 0 0 0-20 20v116H160a20 20 0 0 1-20-20V380a20 20 0 0 1 20-20h708a20 20 0 0 1 20 20v264a20 20 0 0 1-20 20zM170 396a10 10 0 1 0-10-10 10 10 0 0 0 10 10zm36 0a10 10 0 1 0-10-10 10 10 0 0 0 10 10z"/><path fill="#47BAFF" d="M752 344H276v-48a20 20 0 0 1 20-20h436a20 20 0 0 1 20 20zM324 544h388a20 20 0 0 1 20 20v304a20 20 0 0 1-20 20H324a20 20 0 0 1-20-20V564a20 20 0 0 1 20-20zm68 84a8 8 0 0 0 0 16h256a8 8 0 0 0 0-16zm0 72a8 8 0 0 0 0 16h256a8 8 0 0 0 0-16zm0 72a8 8 0 1 0 0 16h256a8 8 0 0 0 0-16z"/></svg>'
};
