// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxSignforBis: IconDefinition = {
  name: 'lx-signfor',
  theme: 'bis',
  icon:
    '<svg viewBox="0 0 1024 1024"><path fill="#0942F0" d="M248 236v52a20 20 0 0 0 20 20h208a20 20 0 0 0 20-20v-52h104a20 20 0 0 1 20 20v612a20 20 0 0 1-20 20H160a20 20 0 0 1-20-20V256a20 20 0 0 1 20-20zm8 200v16h248v-16zm0 76v16h248v-16zm0 76v16h248v-16z"/><path fill="#0942F0" d="M336 236a36 36 0 0 1 72 0h72v44a12 12 0 0 1-12 12H276a12 12 0 0 1-12-12v-44z"/><path fill="#47BAFF" d="M688.36 744V364H776l-.28 380h-87.36zM688.36 348v-32a20 20 0 0 1 20-20H756a20 20 0 0 1 20 20v32.76zM688 760h88v28l-36.4 29.8a12 12 0 0 1-15.2 0L688 788z"/></svg>'
};
