// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxSocketBis: IconDefinition = {
  name: 'lx-socket',
  theme: 'bis',
  icon:
    '<svg viewBox="0 0 1024 1024"><path fill="#0942F0" d="M152 132h720q20 0 20 20v720q0 20-20 20H152q-20 0-20-20V152q0-20 20-20z"/><path fill="#FFF" d="M252 514a262 262 0 1 0 524 0 262 262 0 1 0-524 0z"/><path fill="#47BAFF" d="M508 432h16q4 0 4 4v76q0 4-4 4h-16q-4 0-4-4v-76q0-4 4-4zM424.39 520.76l13.86-8q3.46-2 5.46 1.47l38 65.82q2 3.46-1.46 5.46l-13.86 8q-3.46 2-5.46-1.46l-38-65.82q-2-3.47 1.46-5.47zM554.04 581.25l38-65.82q2-3.46 5.46-1.46l13.86 8q3.46 2 1.46 5.46l-38 65.82q-2 3.47-5.46 1.47l-13.86-8q-3.46-2-1.46-5.47z"/></svg>'
};
