// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxTalkBis: IconDefinition = {
  name: 'lx-talk',
  theme: 'bis',
  icon:
    '<svg viewBox="0 0 1024 1024"><path fill="#47BAFF" d="M284.96 808l-114.24 72.52A20 20 0 0 1 140 863.64V160a20 20 0 0 1 20-20h704a20 20 0 0 1 20 20v92H264.52A12.52 12.52 0 0 0 252 264.52v530.96A12.52 12.52 0 0 0 264.52 808z"/><path fill="#0942F0" d="M888 671.44v193.84a20 20 0 0 1-30.72 16.88l-142.6-90.56q-15.28-10.04-20.4-10H288a20 20 0 0 1-20-20V288a20 20 0 0 1 20-20h580a20 20 0 0 1 20 20zM466 428a6 6 0 0 0-12 0v188a6 6 0 0 0 12 0zm112 0a6 6 0 0 0-12 0v188a6 6 0 0 0 12 0zm112 0a6 6 0 0 0-12 0v188a6 6 0 0 0 12 0z"/></svg>'
};
