// generated by maker/makerIcons automatically
// tslint:disable

export { ApprovePlane } from './plane/ApprovePlane';
export { MailPlane } from './plane/MailPlane';
export { PrinterPlane } from './plane/PrinterPlane';
export { ApproveLinear } from './linear/ApproveLinear';
export { MailLinear } from './linear/MailLinear';
export { PrinterLinear } from './linear/PrinterLinear';
export { ApproveBis } from './bis/ApproveBis';
export { MailBis } from './bis/MailBis';
export { PrinterBis } from './bis/PrinterBis';
