// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxSendPlane: IconDefinition = {
  name: 'lx-send',
  theme: 'plane',
  icon:
    '<svg  viewBox="0 0 1024 1024"><path d="M389.6 632L185.28 427.48a20 20 0 0 1 0-28.28 20.32 20.32 0 0 1 8-4.84l626.96-209.04a20 20 0 0 1 14.92.92z"/><path d="M400 644.76L844.76 200a20 20 0 0 1 0 12.28L635.6 839.4a20 20 0 0 1-25.32 12.68 20.32 20.32 0 0 1-7.8-4.84z"/></svg>'
};
