// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxTrucksPlane: IconDefinition = {
  name: 'lx-trucks',
  theme: 'plane',
  icon:
    '<svg  viewBox="0 0 1024 1024"><path d="M144 536h444v104H332a72 72 0 0 0-144 0h-44zm0-16V268h444v252zM604 520h288v120h-72a72 72 0 0 0-144 0h-72zm0-16V380h208.72L892 501.68V504z"/><path d="M204 642a58 58 0 1 0 116 0 58 58 0 1 0-116 0zM692 642a58 58 0 1 0 116 0 58 58 0 1 0-116 0z"/></svg>'
};
