// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const LxWarehousePlane: IconDefinition = {
  name: 'lx-warehouse',
  theme: 'plane',
  icon:
    '<svg  viewBox="0 0 1024 1024"><path d="M364 584h308v16H364zM364 616h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364zm0 32h308v16H364z"/><path d="M688 887.2V568H348v319.2H144v-468L514 258l374 161.32v468z"/><path d="M516 193.44l372 160.2v51.24L516 244 144 405.68v-51.24l372-161.08z"/></svg>'
};
