// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition } from '../types';

export const MailPlane: IconDefinition = {
  name: 'mail',
  theme: 'plane',
  icon:
    '<svg  viewBox="0 0 1024 1024"><defs><style/></defs><path d="M882.04 357.68l-360 208.48a20 20 0 0 1-20 0l-360-208.48A20 20 0 0 1 132 340.4V792a20 20 0 0 0 20 20h720a20 20 0 0 0 20-20V340.4a20 20 0 0 1-9.96 17.28z"/><path d="M152 189.56h720a20 20 0 0 1 20 20v108.4a20 20 0 0 1-9.96 17.32l-360 208.44a20 20 0 0 1-20 0l-360-208.44A20 20 0 0 1 132 317.96v-108.4a20 20 0 0 1 20-20z"/></svg>'
};
