language: node_js
before_install:
  - export PATH="$HOME/node_modules/.bin:$PATH"
node_js:
  - '10'
before_script:
  - lerna bootstrap
script:
  - npm run test
  - npm run make
  - npm run build
  - npm run make:angular
  - npm run build:angular
branches:
  only:
    - master
    - dev
