// generated by maker/makerIcons automatically
// tslint:disable

import { Manifest } from './types';

export const manifest: Manifest = {
  linear: ['approve', 'mail', 'printer'],
  plane: ['approve', 'mail', 'printer'],
  bis: ['approve', 'mail', 'printer']
};
