// generated by maker/makerIcons automatically
// tslint:disable

import { Manifest } from './types';

export const manifest: Manifest = {
  linear: ['printer'],
  plane: ['printer'],
  bis: ['printer']
};
