// generated by maker/makerIcons automatically
// tslint:disable

import { Manifest } from './types';

export const manifest: Manifest = {
  linear: [
    'lx-calculator',
    'lx-electric',
    'lx-entry',
    'lx-finance',
    'lx-new',
    'lx-printer',
    'lx-schedule',
    'lx-security',
    'lx-send',
    'lx-setting',
    'lx-signfor',
    'lx-socket',
    'lx-take',
    'lx-talk',
    'lx-trucks',
    'lx-warehouse',
    'lx-warning',
    'lx-water',
    'lx-write'
  ],
  plane: [
    'lx-calculator',
    'lx-electric',
    'lx-entry',
    'lx-finance',
    'lx-new',
    'lx-printer',
    'lx-schedule',
    'lx-security',
    'lx-send',
    'lx-setting',
    'lx-signfor',
    'lx-socket',
    'lx-take',
    'lx-talk',
    'lx-trucks',
    'lx-warehouse',
    'lx-warning',
    'lx-water',
    'lx-write'
  ],
  bis: [
    'lx-calculator',
    'lx-electric',
    'lx-entry',
    'lx-finance',
    'lx-new',
    'lx-printer',
    'lx-schedule',
    'lx-security',
    'lx-send',
    'lx-setting',
    'lx-signfor',
    'lx-socket',
    'lx-take',
    'lx-talk',
    'lx-trucks',
    'lx-warehouse',
    'lx-warning',
    'lx-water',
    'lx-write'
  ]
};
