// generated by maker/makerIcons automatically
// tslint:disable

import { IconDefinition, AbstractNode } from './types';

const normalViewBox = '0 0 1024 1024';
const regularViewBox = '64 64 896 896';

const linear = 'linear';
const plane = 'plane';
const bis = 'bis';

type PathArgs = string | ([string, string]);

function getNode(viewBox: string, ...paths: PathArgs[]): AbstractNode {
  return {
    tag: 'svg',
    attrs: { viewBox },
    children: (paths.map((path) => {
      if(Array.isArray(path)) {
        return {
          tag: 'path',
          attrs: {
            fill: path[0],
            d: path[1]
          }
        };
      }
      return {
        tag: 'path',
        attrs: {
          d: path
        }
      };
    }) as any)
  };
}

function getIcon(name: string, theme: 'linear' | 'plane' | 'bis', icon: any): IconDefinition {
  return {
    name,
    theme,
    icon
  };
}

<-- EXPORT_DEFAULT_DIST -->
